name: Build Container

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-build:
    uses: clementreiffers/s3-download-files-capnp-generator/.github/workflows/release-build.yml@main

  build-push-image:
    runs-on: ubuntu-latest
    needs: [ "release-build" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: RELEASE_VERSION=${{ needs.release-build.outputs.build_number }}
          push: true
          tags: ${{ github.repository }}:v${{ needs.release-build.outputs.build_number }}
